### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by zzvv** [unidal/maven-plugins#3]
[ERROR] Failed to execute goal on project codegen: Could not resolve dependencies for project org.unidal.maven.plugins:codegen:jar:2.3.1: Failure to find org.unidal.framework:foundation-service:jar:2.2.0 in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of maven has elapsed or updates are forced -> [Help 1]

**Comment by juliebai** [comment]
Hi
I meet the same problem, do you fix it? Could you share me the solution?
Thanks  a lot!

**Comment by qmwu2000** [comment]
It's fixed now, please check it out.
